name: Build Lambda Functions

on:
  push:
    paths:
      - 'lambda/**'
      - '.github/workflows/build-lambda.yml'
  pull_request:
    paths:
      - 'lambda/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: lambda/post-confirmation/package-lock.json

      - name: Build PostConfirmation Lambda
        run: |
          cd lambda/post-confirmation
          npm ci
          npm run package

      - name: Commit Lambda ZIP
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add lambda/post-confirmation.zip
          git diff --staged --quiet || git commit -m "chore: rebuild lambda package [skip ci]"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

